default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: gmail_client_development

test:
  <<: *default
  host: localhost
  database: gmail_client_test

production:
  <<: *default
  database: gmail_client_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>